"""Provider capability and pricing assumptions for routing eligibility."""

from __future__ import annotations

from typing import Any, Dict, List

CAPABILITY_MATRIX: List[Dict[str, Any]] = [
    {
        "provider": "openai-codex",
        "model": "codex-subscription",
        "supports_vision": True,
        "supports_tools": True,
        "supports_json_schema": True,
        "supports_reasoning": True,
        "context_window_tokens": None,
        "max_output_tokens": None,
        "supports_cache_read_pricing": False,
        "cache_hit_usd_per_mtok": None,
        "input_usd_per_mtok": None,
        "output_usd_per_mtok": None,
        "known_quirks": ["subscription_quota_not_direct_marginal_spend"],
        "data_policy": "unknown",
        "spend_guard_required": False,
        "source_url": "https://chatgpt.com/backend-api/wham/usage",
    },
    {
        "provider": "deepseek",
        "model": "deepseek-v4-pro",
        "supports_vision": False,
        "supports_tools": True,
        "supports_json_schema": True,
        "supports_reasoning": True,
        "context_window_tokens": None,
        "max_output_tokens": None,
        "supports_cache_read_pricing": True,
        "cache_hit_usd_per_mtok": None,
        "input_usd_per_mtok": None,
        "output_usd_per_mtok": None,
        "known_quirks": ["reasoning_content_history_format", "no_vision_in_current_luis_routing_context"],
        "data_policy": "unknown",
        "spend_guard_required": True,
        "source_url": "https://api-docs.deepseek.com/quick_start/pricing",
    },
    {
        "provider": "deepseek",
        "model": "deepseek-v4-flash",
        "supports_vision": False,
        "supports_tools": True,
        "supports_json_schema": True,
        "supports_reasoning": True,
        "context_window_tokens": None,
        "max_output_tokens": None,
        "supports_cache_read_pricing": True,
        "cache_hit_usd_per_mtok": None,
        "input_usd_per_mtok": None,
        "output_usd_per_mtok": None,
        "known_quirks": ["cheap_lane_candidate", "no_vision_in_current_luis_routing_context"],
        "data_policy": "unknown",
        "spend_guard_required": True,
        "source_url": "https://api-docs.deepseek.com/quick_start/pricing",
    },
    {
        "provider": "mimo",
        "model": "mimo-v2.5-pro",
        "supports_vision": False,
        "supports_tools": None,
        "supports_json_schema": None,
        "supports_reasoning": True,
        "context_window_tokens": None,
        "max_output_tokens": None,
        "supports_cache_read_pricing": True,
        "cache_hit_usd_per_mtok": None,
        "input_usd_per_mtok": None,
        "output_usd_per_mtok": None,
        "known_quirks": ["needs_benchmark_against_deepseek_before_promotion"],
        "data_policy": "unknown",
        "spend_guard_required": True,
        "source_url": "https://platform.xiaomimimo.com/docs/en-US/price/pay-as-you-go",
    },
    {
        "provider": "gemini",
        "model": "gemini-2.5-flash",
        "supports_vision": True,
        "supports_tools": True,
        "supports_json_schema": True,
        "supports_reasoning": True,
        "context_window_tokens": None,
        "max_output_tokens": None,
        "supports_cache_read_pricing": None,
        "cache_hit_usd_per_mtok": None,
        "input_usd_per_mtok": None,
        "output_usd_per_mtok": None,
        "known_quirks": ["prior_unbounded_fallback_burned_300_gcp_credit_in_two_days"],
        "data_policy": "unknown",
        "spend_guard_required": True,
        "source_url": "https://ai.google.dev/gemini-api/docs/pricing",
    },
]


def get_capability_matrix() -> List[Dict[str, Any]]:
    return [dict(row) for row in CAPABILITY_MATRIX]
